function interface(INOUT)
	INOUT.float = Type:Float()
	INOUT.vector2f = Type:Vec2f()
	INOUT.vector3f = Type:Vec3f()
	INOUT.vector4f = Type:Vec4f()
	INOUT.integer = Type:Int32()
	INOUT.integer64 = Type:Int64()
	INOUT.vector2i = Type:Vec2i()
	INOUT.vector3i = Type:Vec3i()
	INOUT.vector4i = Type:Vec4i()
	INOUT.bool = Type:Bool()
	INOUT.string = Type:String()
end
