#ifndef PROGRAMDEFINE_H
#define PROGRAMDEFINE_H
#include <QString>
#include <QStringLiteral>
#include <string>

#define JSON_X                      QString("x")
#define JSON_Y                      QString("y")
#define JSON_Z                      QString("z")
#define JSON_W                      QString("w")
#define JSON_LAST_OBJECT_ID         QString("lastObjectId")
#define JSON_UNIFORM                QString("Uniform")
#define JSON_NODE                   QString("node")
#define JSON_ACTIVE_NODE            QString("active_node")
#define JSON_CHILD                  QString("child")
#define JSON_NAME                   QString("name")
#define JSON_OBJECTID               QString("objectId")
#define JSON_TRANSLATION            QString("translation")
#define JSON_ROTATION               QString("rotation")
#define JSON_SCALE                  QString("scale")
#define JSON_BASIC_PROPERTY         QString("basicProperty")
#define JSON_KEYFRAME               QString("keyFrame")
#define JSON_TYPE                   QString("type")
#define JSON_MATERIAL               QString("material")
#define JSON_MESH                   QString("mesh")
#define JSON_CUSTOM_PROPERTY        QString("customProperty")
#define JSON_PROPERTY               QString("property")
#define JSON_CURVE                  QString("curve")
#define JSON_SAMPLEPROPERTY         QString("sampleProperty")
#define JSON_CURVEBINDING           QString("curveBinding")
#define JSON_SYSTEMPROPERTY         QString("systemProperty")
#define JSON_ANIMATIONPROPERTY      QString("animationProperty")
#define JSON_DATA_TYPE              QString("dataType")
#define JSON_DATA                   QString("Data")
#define JSON_INTERPOLATION_TYPE     QString("InterpolationType")
#define JSON_LEFT_TANGENT           QString("LeftTangent")
#define JSON_RIGHT_TANGENT          QString("RightTangent")
#define JSON_LEFT_KEYFRAME          QString("LeftKeyFrame")
#define JSON_RIGHT_KEYFRAME         QString("RightKeyFrame")
#define JSON_LEFT_DATA              QString("LeftData")
#define JSON_RIGHT_DATA             QString("RightData")
#define JSON_POINT_LIST             QString("pointList")
#define JSON_START_TIME             QString("start")
#define JSON_END_TIME               QString("end")
#define JSON_LOOP_COUNT             QString("loopCount")
#define JSON_UPDATE_INTERVAL        QString("updateInterval")
#define JSON_VALUE                  QString("value")
#define JSON_ANIMATION              QString("animation")
#define JSON_ACTIVE_ANIMATION       QString("active_animation")
#define JSON_MATRX_OO               QString("m00")
#define JSON_MATRX_O1               QString("m01")
#define JSON_MATRX_O2               QString("m02")
#define JSON_MATRX_O3               QString("m03")
#define JSON_MATRX_10               QString("m10")
#define JSON_MATRX_11               QString("m11")
#define JSON_MATRX_12               QString("m12")
#define JSON_MATRX_13               QString("m13")
#define JSON_MATRX_20               QString("m20")
#define JSON_MATRX_21               QString("m21")
#define JSON_MATRX_22               QString("m22")
#define JSON_MATRX_23               QString("m23")
#define JSON_MATRX_30               QString("m30")
#define JSON_MATRX_31               QString("m31")
#define JSON_MATRX_32               QString("m32")
#define JSON_MATRX_33               QString("m33")
#define JSON_RENDER_MODE            QString("renderMode")
#define JSON_WINDING                QString("winding")
#define JSON_CULLING                QString("culling")
#define JSON_BLENDING               QString("blending")
#define JSON_BLEND_OPT_COLOR        QString("blendOpreationColor")
#define JSON_BLEND_OPT_ALPHA        QString("blendOpreationAlpha")
#define JSON_SRC_COLOR_FACTOR       QString("sourceColorFactor")
#define JSON_SRC_ALPHA_FACTOR       QString("sourceAlphaFactor")
#define JSON_DEST_COLOR_FACTOR      QString("destinationColorFactor")
#define JSON_DEST_ALPHA_FACTOR      QString("destinationAlphaFactor")
#define JSON_DEPTH_COMPARE          QString("depthCompare")
#define JSON_DEPTH_WRITE            QString("depthWrite")
#define JSON_COLOR_WRITE            QString("colorWrite")
#define JSON_RED                    QString("red")
#define JSON_GREEN                  QString("green")
#define JSON_BLUE                   QString("blue")
#define JSON_ALPHA                  QString("alpha")
#define JSON_SHADER_REFERENCE       QString("shaderReference")
#define JSON_BITMAP_REFERENCE       QString("bitmapReference")
#define JSON_MIN_FILTER             QString("minFliter")
#define JSON_MAG_FILTER             QString("magFliter")
#define JSON_ANISOTROPIC_SAMPLES    QString("anisotropicSamples")
#define JSON_WRAPE_MODEU            QString("wrapeModeU")
#define JSON_WRAPE_MODEV            QString("wrapeModeV")
#define JSON_UNIFORM_NAME           QString("uniformName")
#define JSON_TEXTURE                QString("texture")
#define JSON_FLOAT                  QString("Float")
#define JSON_INT                    QString("Int")
#define JSON_BOOL                   QString("Bool")
#define JSON_STRING                 QString("String")
#define JSON_SHADER                 QString("shader")
#define JSON_VERTEX_SHADER          QString("vertexShader")
#define JSON_FRAGMENT_SHADER        QString("fragmentShader")
#define JSON_BITMAP                 QString("bitmap")
#define JSON_RESOURCE               QString("resource")
#define JSON_GENERATE_MIPMAPS       QString("generateMipMaps")
#define JSON_MATERIAL_REF			QString("materialReference")
#define PTX_SCENE_NAME				QString("Scene")
#define PTW_USED_ANIMATION_NAME		std::string("UsedAnimationName")
#define PTW_PRE_CURVES_ONE_PROP		std::string("Multi-CurvesSingleProp-")
#define PTW_PRE_ANIMATS_ONE_CURVE   std::string("Multi-AnimationsSingleCurve-")
#define PTW_SUF_ANIMAT_DOMAIN	    std::string("_domain")
#define PTW_SUF_CURVE_INETERAL		std::string("_interal")
#define PTW_SCALE_DIVIDE_VALUE		std::string("ScaleDivideValue.outputX")
#define PTW_SCALE_DIV_MUL_VALUE		std::string("ScaleDivResultMulValue.outputX")
#define PTW_FRAG_SYS_OPACITY		std::string("Sys_Opacity")
#define PTW_FRAG_SYS_DOT_OPACITY	std::string("Sys_DotOpacity")
#define PTW_FRAG_SYS_DOT_SIZE		std::string("Sys_DotSize")
#define PTW_FRAG_SYS				std::string("Sys_")


#define PTW_SINGLE_AN_INTERVAL		std::string("Animation_domain")

// externalModelValue
#define PTW_EX_HUD_NAME				std::string("HUD")
#define PTW_EX_CON_IPA_ICON_C		std::string("Content_IPAIconTransformation_C")
#define PTW_EX_HUD_CON_IPA_ICON_C	std::string("HUD_Content_IPAIconTransformation_C")
#define PTW_EX_TRIGGLE_ANIMATION	std::string("Animation")

// Sys
#define PTW_EX_SCALE_NAME			std::string("Scale")
#define PTW_EX_OPACITY_NAME			std::string("Opacity")
#define PTW_EX_DOT_OPACITY			std::string("DotOpacity")
#define PTW_EX_DOT_SIZE				std::string("DotSize")

// internalModelValue
#define PTW_IN_V4					std::string("_V4")
#define PTW_IN_COLOR_MODE			std::string("colorMode_color")
#define PTW_IN_U_COLOR				std::string("u_color")

// projectName
#define PRO_ELLIE					std::string("Ellie")
#define PRO_GASSTATION				std::string("GasStation")

#endif // PROGRAMDEFINE_H
